In [1]:
import numpy as np

### Numpy Array

In [2]:
# numpay arrayleri python listelerine benziyor
## ama onların aksine farklı veri tiplerinde elemanlar içermez Tek veri tipinde elemanları olması gerekiyor.

### Listlerden Array Yaratmak

In [3]:
x = np.array( [1, 2, 3, 4] )

In [4]:
x

array([1, 2, 3, 4])

In [5]:
type(x)

numpy.ndarray

In [6]:
y = np.array( ["a", "b", "c"] )

In [7]:
y

array(['a', 'b', 'c'], dtype='<U1')

In [8]:
type(y)

numpy.ndarray

### Array elemanları homojen olmalı

In [9]:
# hem string hem integer bulundurursam---> hepsi stringe cast edilir

In [10]:
z = np.array( [2, 3, 4, "a"] )

In [11]:
z

array(['2', '3', '4', 'a'], dtype='<U11')

In [12]:
a = np.array( [1, 2.9, 3, 5] )

In [13]:
a

array([1. , 2.9, 3. , 5. ])

In [14]:
type(a)

numpy.ndarray

In [16]:
x = np.array( [1,2,"3", "a", 4,7, 9] )

In [17]:
x

array(['1', '2', '3', 'a', '4', '7', '9'], dtype='<U11')

### Array Data Tipini Manuel Belirtmek

In [18]:
# Array' in elemanlarının tipinin ne olacağını özellikle belirtebiliriz

In [19]:
x = np.array( [1,2,3,4.6] )

In [20]:
x

array([1. , 2. , 3. , 4.6])

In [21]:
x = np.array(  [1,2,3,4.6], dtype = int )

In [22]:
x

array([1, 2, 3, 4])

In [23]:
x = np.array(  [1,2,3,4.6], dtype = "str")

In [24]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [25]:
x = np.array( ["a"], dtype = "int32")

ValueError: invalid literal for int() with base 10: 'a'

In [27]:
x = np.array( ["5"], dtype = "int32")

In [28]:
x

array([5])

### Elemanları 0'lardan Oluşan Array Oluşturmak

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros( 10, dtype  = str )

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [6]:
np.zeros( 10, int )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Elemanları 0'lardan Oluşan Multidimensional Array Oluşturmak

In [7]:
# 3 row(satır) ve 4 column(sütun)' u olan bir array oluşturalım.
# boyutu tuple olarak veriyorum çünkü np.zeros(shape, datatype) bekliyor
## ve virgülle ayırınca ona datatype verdiğimizi düşünüyor
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [10]:
# tuple yerine list gibi de verebilirdim shape i
np.zeros( [3,4] )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros( [3,8,8] )

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [13]:
np.zeros( (1,2), dtype = int )

array([[0, 0]])

In [14]:
np.zeros( (2,3), dtype = bool )

array([[False, False, False],
       [False, False, False]])

In [18]:
a = np.zeros([2,2,2,3])

In [19]:
a.shape

(2, 2, 2, 3)