In [4]:
import numpy as np

#### stack: stack mantığını yeni dimension ekleyip o dimension üzerinde concentenation yaparak da sağlayabiliriz

In [5]:
a = np.array( [1,2,3,4])

In [6]:
b = np.array( [5,6,7,8])

In [7]:
a.shape

(4,)

In [8]:
b.shape

(4,)

In [26]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.concatenate([a,b], axis = 0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.concatenate( [a,b] , axis = 1 )

AxisError: axis 1 is out of bounds for array of dimension 1

#### default olarak -0 da birleştirme yapacak

In [14]:
np.stack( [a,b] ) # axis = 0 üzerinde birleştirir

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
np.stack( [a,b] ).shape # stack ile dimension kazandı

(2, 4)

In [16]:
arrays = [np.random.randn(3, 4) for _ in range(10)]

In [17]:
arrays

[array([[ 1.1842813 ,  0.91135896, -0.88579772, -0.49772469],
        [ 1.01358773,  0.47293236, -1.65283004, -1.49167657],
        [-0.35026987,  1.88568219,  0.42796922,  0.50808188]]),
 array([[-2.10576734e-01,  8.17205590e-01,  4.78127604e-01,
          2.68927029e-01],
        [-1.31148258e+00, -6.70563151e-01, -6.63529329e-01,
          3.46174361e-01],
        [-7.59275788e-01,  1.23818053e+00, -9.42834315e-01,
         -1.02861693e-03]]),
 array([[ 0.70007269,  1.14981003, -0.68318105, -2.06867386],
        [ 1.0637174 ,  0.44506073, -0.36990334, -0.60742257],
        [ 0.79393508, -1.24337886,  1.42520919,  1.55835945]]),
 array([[ 0.1018272 ,  0.32974081, -0.43410852,  1.83354345],
        [ 0.05895334,  1.61027489, -0.54231124, -0.26617694],
        [-0.66146279, -0.39707952, -0.54119859,  0.77049706]]),
 array([[-0.15234005, -0.58859035, -0.09858198, -1.70434349],
        [ 0.03554032, -0.80304033,  0.3531662 , -0.21444372],
        [-0.50822649, -1.42830334,  0.0939001 , -

In [19]:
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [20]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [22]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [24]:
np.random.randn(3,4)

array([[-1.64854823, -0.84169585,  0.46931759,  0.65611288],
       [ 0.16488677,  0.22231951,  0.25531581, -0.0802786 ],
       [-0.89775934, -0.94788582,  0.42098892,  1.20726637]])

In [27]:
a

array([1, 2, 3, 4])

In [28]:
b

array([5, 6, 7, 8])

In [32]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
np.stack((a,b), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
np.stack((a,b), axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [39]:
np.stack((a,b), axis=-1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### stack mantığı yeni bir dimension yarat, üzerinde birleştir

 ### stack implementation using list

In [43]:
stack = [ ]

In [44]:
# append( ) function to push element in the stack
stack.append(' a ')
stack.append(' b ')
stack.append(' c ')

In [45]:
stack

[' a ', ' b ', ' c ']

In [46]:
print('ınitial stack')
print(stack)

ınitial stack
[' a ', ' b ', ' c ']


In [47]:
# pop( ) function to pop element from stack in LIFO order(Last In First Out)
print('/nElements popped from stack: ')
print(stack.pop( ))

/nElements popped from stack: 
 c 


In [48]:
print(stack.pop( ))

 b 


In [49]:
print(stack.pop( ))

 a 


In [50]:
print(stack.pop( )) #IndexError: pop from epmty list

IndexError: pop from empty list

In [51]:
print(stack)

[]


### implementation using collections.deque

##### deque is preferred over list in the cases where we need quicker append and pop operations from both the ends of container

In [3]:
from collections import deque

In [4]:
stack = deque()

In [5]:
# append() function to push element in the stack
stack. append('a')

In [6]:
type(stack)

collections.deque

In [7]:
stack.append('b')

In [8]:
stack.append('c')

In [9]:
print('Initial stak: ')
print(stack)

Initial stak: 
deque(['a', 'b', 'c'])


In [10]:
# pop() function to pop elements from stack in LIFO order
print("Elements popped from stack: ")
print(stack.pop())
print(stack.pop())
print(stack.pop())

Elements popped from stack: 
c
b
a


In [11]:
print('\nStack after elements are popped: ')
print(stack)


Stack after elements are popped: 
deque([])


### implementation using queue module

#### queue module also has a LIFO Queue, which is basically a Stack. Data is inserted into Queue using the put() function and get() takes data out from the Queue

In [78]:
from queue import LifoQueue

In [79]:
# initializing a stack
stack = LifoQueue(maxsize=3)

In [80]:
# qsizie() show the number of elements in the stack
print(stack.qsize() )

0


In [84]:
print(stack.maxsize)

3


In [85]:
# put() function to push element in the stack
stack.put('a')
stack.put('b')
stack.put('c')

In [88]:
print(stack)

In [94]:
print("Full: ", stack.full())


Full:  True


In [95]:
print("Size: ", stack.qsize())

Size:  3


In [96]:
# get() function to pop element from stack in LIFO order
print('\nElements popped from the stack')
print(stack.get())
print(stack.get())
print(stack.get())


Elements popped from the stack
c
b
a


In [97]:
print("Empty: ", stack.empty())

Empty:  True


ModuleNotFoundError: No module named 'jupyterthemes'