In [1]:
import numpy as np

## np.split(array_name, indices_or_sections, axis = 0)

### list leri de split edebilirim arrayleri de, her ikisinde de array çevirir

In [4]:
l = np.arange(0,81,10)
l

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [5]:
np.split(l, [2,6])

[array([ 0, 10]), array([20, 30, 40, 50]), array([60, 70, 80])]

In [11]:
type(np.split(l, [2,6]))

list

In [13]:
np.split(l, [2,6]) [0]

array([ 0, 10])

In [14]:
type(np.split(l,[2,6]) [0] )

numpy.ndarray

### splitin sonucunu birden çok değişkene eşitleme(multivariable assigment)

In [6]:
# mini örnek
a, b = (1, 10)

In [10]:
l

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [8]:
x, y, z = np.split(l, [3,7])

In [9]:
print(x)
print(y)
print(z)

[ 0 10 20]
[30 40 50 60]
[70 80]


### vsplit  : split array into multiple sub-arrays vertically(row-wise)

In [15]:
a = np.arange(20).reshape(2,10)

In [16]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [17]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [18]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
x = np.arange(16.0).reshape(4,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
np.