## Sorting

In [2]:
import numpy as np

In [6]:
a = np.array( [20, 32,5, 30, 27] )

#### güncelleme yapmayan sort

In [7]:
np.sort(a)

array([ 5, 20, 27, 30, 32])

In [8]:
a

array([20, 32,  5, 30, 27])

#### güncelleme yapan sort/  funciton call

In [11]:
a.sort()   
### a.sort() = inplace(a = np.sort(a) )

In [12]:
a

array([ 5, 20, 27, 30, 32])

### np.argsort(array_name)

In [14]:
b = np.array( [2,6,1,5,4,3])

In [15]:
#küçükten büyüğe sıralanmış elemanların indekslerini veriyor
idxs = np.argsort(b)
idxs

array([2, 0, 5, 4, 3, 1], dtype=int64)