In [1]:
import numpy as np

### mulidimensional arraylerin elemanlarına ulaşmak

In [2]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a[0]

array([1, 2, 3, 4, 5])

In [6]:
a[0][2]

3

In [8]:
a[0,2]

3

In [9]:
a[0][3] == a[0,3]

True

In [10]:
a.ndim

2

In [11]:
a[0].ndim

1

In [12]:
a[0].shape

(5,)

##### Eğer array oluştururken int ve floatları aynı anda oluşturmaya çalışıyorsam en genel hali neyse ona cast eder.

#### Ama eğer array oluşturulduktan sonra int dolu arraye float eklersem en son eklenen float değeri int olur, arrayin veri tipi değişmez

In [13]:
# Arrayin veri tipi neyse son eklenen değer ona cast olur, array in veri tipi değişmez!
a[1][1] = 20.40

In [14]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
a[1][1] = " 30 "

In [16]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
#value error
# floatın stringini int stringe çevirip sonra tamamen integera cast edemiyor
# çift aşamalı cast edemediği için error veriyor gibi düşün
a[1][1] = " 30.5 "
#a

ValueError: invalid literal for int() with base 10: ' 30.5 '

In [21]:
# value error
a[1][1] = "a"

ValueError: invalid literal for int() with base 10: 'a'

### slice indexing

In [22]:
a = np.arange(1,21).reshape(4,5)

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
#başlnagıç indeksi dahil; bitiş indeksi dahil değil
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[2: ]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
# 1.indeksten başla, sona kadar git, step size = 2 olacak şekilde
a[1 : : 2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [31]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
# istenilen rowu alma
a[ :,3]

array([ 4,  9, 14, 19])

In [35]:
a[0,2:4]

array([3, 4])

In [38]:
a[ :2 , 4]

array([ 5, 10])

## array[x, start:stop, y]

In [39]:
a[:2, :3]

array([[1, 2, 3],
       [6, 7, 8]])

In [40]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

### array[start:stop:step_size]