In [1]:
import numpy as np

In [2]:
# FANCY INDEXİNG
# Şimdiye kadar hep belirli elemanları, belirli kesitlerdeki elemanları, veya belirli sayıda
# atlaya atlaya elemanları almayı gördük. Fancy indexing ile birkaç tane belirli indeksteki 
# elemanları bana döndür diyebilmiş olacağız

In [3]:
x = np.arange(1,15)

In [4]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
idxs = [4,5,7,11]

In [6]:
x[idxs]

array([ 5,  6,  8, 12])

In [8]:
idxs_new = [4,11,5,7]

In [9]:
x[idxs_new] == x[idxs]

array([ True, False, False, False])

In [10]:
x[idxs_new]

array([ 5, 12,  6,  8])

In [11]:
# index listesine hangi sıra ile verirsen o sıra ile çağırır. array[index_number_lists]

In [12]:
a = np.arange(1,13).reshape(3,4)

In [13]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
b = a[1,(1,3)]

In [15]:
b

array([6, 8])

In [16]:
b.ndim

1

In [17]:
a[1, ]

array([5, 6, 7, 8])