In [1]:
import numpy as np

## SUBARRAY

In [2]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
b = a[:2,:3]
b

array([[1, 2, 3],
       [6, 7, 8]])

In [5]:
b.ndim

2

In [6]:
b[0][0] = 100

In [7]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [8]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

## a'nın subarrayi b'de değişiklik yapıldığında b'deki değişikliğin a'ya etki etmemesi için copy üzerinde çalışabiliriz

In [10]:
c = a[:2, :3].copy()

In [11]:
c

array([[100,   2,   3],
       [  6,   7,   8]])

In [12]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [13]:
c[0][0] = 50

In [14]:
c

array([[50,  2,  3],
       [ 6,  7,  8]])

In [15]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])