In [1]:
import numpy as np

### conditional indexing

In [2]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a>5
#boolean array döndürmesini bekliyorum

array([False, False, False, False, False,  True,  True,  True,  True])

In [5]:
a[a>5]

array([6, 7, 8, 9])

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
filt = a < 5

In [8]:
filt

array([ True,  True,  True,  True, False, False, False, False, False])

In [9]:
a[filt]

array([1, 2, 3, 4])

In [10]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [14]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [15]:
a[a==b]

array([3, 4, 5, 7, 8])

### a[filter]

In [16]:
b[a==b]

array([3, 4, 5, 7, 8])

In [17]:
a[a==b] == b[b==a]

array([ True,  True,  True,  True,  True])

In [19]:
# normalde 'and', 'or' ile kurduğumuz mantığı numpy'da kulanamıyoruz,error 
(a > 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
(a < 3) | (a > 5 )
# veya

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [23]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
(a < 3) & (a > 5 )
# ve

array([False, False, False, False, False, False, False, False, False])

In [25]:
filt2 = (a <3) | (a>5)

In [27]:
a[filt2]

array([1, 2, 6, 7, 8, 9])

In [28]:
a[(a>3) & (a<=5)]

array([4, 5])

### filtrenin değili

In [29]:
a = np.arange(1,21).reshape(4,5)

In [30]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
filt = a < 5

In [32]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [33]:
a[filt]

array([1, 2, 3, 4])

In [34]:
filt = (a>5) & (a<9)

In [35]:
a[filt]

array([6, 7, 8])

### Filtrenin değili için tilda '~' kullanılır. 

In [38]:
~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [39]:
a[~((a>5) & (a<9))]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Multidimensional Array'lerde Conditioal Indexing

In [40]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
type(a)

numpy.ndarray

In [42]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [43]:
type(a<7)

numpy.ndarray

In [44]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [45]:
a[a<7].shape

(6,)

In [46]:
type(a[a<7])

numpy.ndarray

In [49]:
aa = np.array([1, 2, 3, None])

In [52]:
aa

array([1, 2, 3, None], dtype=object)

In [53]:
aa == None

array([False, False, False,  True])

In [54]:
aa[i] = None
i

NameError: name 'i' is not defined

In [75]:
sayi = 0
for sayi in aa:
    if aa[sayi] == None:
        print(sayi)
    else:
        sayi += 1

3


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
aa

In [1]:
aa = np.array([1, 2, 3, None])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
aa = np.array([1, 2, 3, None])

In [4]:
for i=0, i<len(aa),i++:
    aa[i] == None
    print(i)
    

SyntaxError: invalid syntax (<ipython-input-4-5e17d3032221>, line 1)

In [5]:
for sayi in aa:
    if sayi == None:
        print(sayi)

None


In [6]:
for i in range(len(aa)):
    if aa[i] == None:
        print(aa[i])

None


In [7]:
for i in range(len(aa)):
    if aa[i] == None:
        print(i)

3


In [8]:
x = np.arange(-5,3).reshape(2,4) 

In [9]:
a

NameError: name 'a' is not defined

In [17]:
x

array([[-5, -4, -3, -2],
       [-1,  0,  1,  2]])

In [19]:
x[(x<0) | (x==2)]

array([-5, -4, -3, -2, -1,  2])

In [20]:
x[(x<0) & x==2]

array([], dtype=int32)

In [21]:
x[x[(x<0)]

SyntaxError: unexpected EOF while parsing (<ipython-input-21-5fc45fa16482>, line 1)

In [22]:
x[(x<0) ]

array([-5, -4, -3, -2, -1])

In [23]:
x[(x==2)]

array([2])

In [24]:
x[(x<0) | (x==2)]

array([-5, -4, -3, -2, -1,  2])