In [2]:
import numpy as np

### all : verilen şart TÜM ELEMANLARDA sağlaıyor mu kontrolünü yapar



In [3]:
x = np.arange(20).reshape(4,5)

In [4]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
x >= 1

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
x > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [8]:
np.all(x > -1)

True

In [9]:
np.all(x > 5)

False

In [11]:
filt = x > -1

In [12]:
filt

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [14]:
np.all(filt)

True

In [18]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
np.all(x > 5, axis = 1)

array([False, False,  True,  True])

In [20]:
np.all(x < 5, axis = 0)

array([False, False, False, False, False])

In [21]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
np.all(a > 8, axis = 1)

array([False, False,  True,  True])

### np.any: Verilen şart HERHANGİ BİR ELEMANDA sağlanıyor mu kontrolünü yapar

In [23]:
aa = np.arange(20).reshape(4,5)

In [24]:
aa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
aa > 17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [26]:
np.any(aa > 20)

False

In [27]:
np.any(aa > 14)

True

In [28]:
np.any(aa > 17, axis=0)

array([False, False, False,  True,  True])

In [29]:
np.any(aa > 17, axis = 1)

array([False, False, False,  True])