### Aralığı Eşit Uzaklıktaki Noktalara Bölmek
## np.linspace()

In [1]:
# Belirlenen [başlangıç, bitiş] değerine göre, başlangıç ve bitişi dahil edecek şekilde
## aralığı eşit uzaklıkta  noktalara bölmeye yarar.

In [3]:
import numpy as np

In [4]:
# Default olarak 50 nokta döndürüyor.
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [5]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [7]:
np.linspace(1,100, num =10, endpoint = False )

array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1])

### Kaç Parçaya Böleceğini Göstermek

In [8]:
np.linspace(1,2, num = 3)

array([1. , 1.5, 2. ])

In [9]:
np.linspace( 1,2, num=3, endpoint = False )

array([1.        , 1.33333333, 1.66666667])

In [10]:
# 0 ve 1 arasında (0,1 dahil olacak şekilde) 30 nokta üretmek
np.linspace( 0, 1, 30 )

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [14]:
np.linspace(1.2, 3.6, 10, endpoint= True )

array([1.2       , 1.46666667, 1.73333333, 2.        , 2.26666667,
       2.53333333, 2.8       , 3.06666667, 3.33333333, 3.6       ])

In [15]:
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])