### Normal Distribution'dan Çekilmiş Değerler ile Array Oluşturmak

In [1]:
import numpy as np

In [2]:
# mean
# std
# array size

In [3]:
np.random.normal(0, 1, (4,5))

array([[-0.77376007, -0.06872272, -0.61672961,  0.08938283,  1.43166324],
       [-0.39624279,  0.48210526,  0.13972378,  0.69631913, -0.41873052],
       [ 0.44861346,  0.68215999, -0.51238292,  0.93844202,  0.80605063],
       [-0.16937677, -1.58716997, -1.14993022,  0.04018125, -0.77079584]])

In [4]:
np.random.normal(0, 100, (4,5))

array([[  21.20283583,   42.24891159,  113.14321976,  -88.50775035,
         -68.34036991],
       [ -18.59514762, -177.62032558,  -78.59284123,   24.20575394,
         -13.86326035],
       [ 120.30044488,   22.78349522, -189.33504345,   61.8777189 ,
         -35.79340712],
       [ -48.97302293,   80.81838641,  -89.84476458,   98.73604216,
          43.11378046]])

In [5]:
np.random.normal(10, 1, (4,5))

array([[ 9.64100439, 11.52092217, 10.82026319,  9.11115757,  9.34570739],
       [ 9.72675136,  9.59014069, 10.35047545,  9.52475896,  8.54121488],
       [ 8.86181629, 10.63160636,  9.07804688,  9.45639479, 10.0003032 ],
       [10.34156847,  9.7175774 ,  9.01523792, 11.29216737, 10.3806666 ]])