In [1]:
# The term broadcasting refers to how numpy treats arrays with 
# different Dimension during arithmetic operations which lead to certain constraints,
# the smaller array is broadcast across the larger array so that they have compatible shapes.  

### Example#1: Single Dimension Array

In [1]:
import numpy as np

In [2]:
a = np.array( [17, 11, 19] ) # 1x3 dimension array

In [3]:
print(a)

[17 11 19]


In [6]:
b = 3
print(b)

3


In [7]:
# broadcasting happened because of
# miss match in array Dimension
c = a + b
print(c)

[20 14 22]


### Example#2: Two Dimensioanal Array

In [8]:
A = np.array( [ [11, 22, 33], [10, 20, 30] ] )
print(A)

[[11 22 33]
 [10 20 30]]


In [9]:
b = 4
print(b)

4


In [11]:
C = A + b
print(C)

[[15 26 37]
 [14 24 34]]


### Example3:

In [12]:
v = np.array( [12, 24, 36] )
w = np.array( [45, 55] )

In [15]:
# to compute an outer product we first
# reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output
# of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3,1)) * w )

[[ 540  660]
 [1080 1320]
 [1620 1980]]


In [19]:
X = np.array([[12, 22, 33], [45, 55, 66]])
print(X)

[[12 22 33]
 [45 55 66]]


In [20]:
print(np.reshape(v, (3,1)))

[[12]
 [24]
 [36]]


In [21]:
print(v)

[12 24 36]


In [17]:
# x has shape  2x3 and v has shape (3, )
# so they broadcast to 2x3,
print(X + v)

[[ 24  46  69]
 [ 57  79 102]]


In [8]:
d={}

for _ in range(20000):
    val=np.random.randint(1,11)
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1