In [1]:
import numpy as np

In [2]:
# (low,high)

In [3]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#matris boyutu kare olmadığında diagonalleri 1 yapıp kalanına sıfır koyuyor.
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [6]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array İşlemleri

In [7]:
# * operatörü iki list arasında tanımsızdır, hata verir

a = [1, 2, 3]
b = [2, 4, 8]

a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
# list ile integer çarpılırsa concatenation yapar

[2, 5, 7] * 3

[2, 5, 7, 2, 5, 7, 2, 5, 7]

In [10]:
# list ile list toplanırsa da concatenation yapar
[2,4,8] + [2,4,8]

[2, 4, 8, 2, 4, 8]

### ama bu operatörler numpy arrayleri üzerinde beklenilen gibi çalışır, concatenation yapmaz

### * operatörü iki numpy arrayi arasında tanımlıdır, ELEMENT-WISE (eleman bazlı) çarpma yapar

In [13]:
x = np.array( [1, 2, 3] )
y = np.array( [2, 4, 8] )

x * y

array([ 2,  8, 24])

In [15]:
a = [1, 2, 3]
b = [5, 7, 9]

a + b  #concat yapar

[1, 2, 3, 5, 7, 9]

In [17]:
c = np.array( [1, 2, 3] )
d = np.array( [5, 7, 9] )

c + d  #toplama yapar

array([ 6,  9, 12])

### Array Attributes

## SHAPE

In [29]:
a = np.zeros((3,4))
a.shape

(3, 4)

In [30]:
b = np.zeros( (2, 4, 5) )
b.shape
b

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

## NDİM

In [31]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
b = np.zeros( (2, 4, 5,2) )
b

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [38]:
a.ndim

2

In [39]:
b.ndim

4

## SIZE

In [44]:
# kaç eleman olduğunu söylüyor
#dimensionların çarpımı
a.size

12

In [45]:
b.size

80

## DTYPE

In [46]:
a.dtype

dtype('float64')

In [47]:
b = np.zeros( (2, 4, 5,2), dtype = int )

In [48]:
b

array([[[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]]])

In [49]:
b.dtype

dtype('int32')

## Reshaping

In [50]:
x = np.arange(1, 11)

In [51]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
x.ndim

1

In [53]:
x.size

10

In [54]:
x.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
x.reshape(2,5).ndim

2

In [57]:
x # reshape x üzerinde kalıcı değişiklik yapmaz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [59]:
x.reshape(5,2).ndim

2

## -1 ile Boyuta Karar Vermek

In [60]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
x.reshape(-1,2)
# belli size ı ikiye bölecek -1 yerine 5 algılayacak, infer edecek

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [63]:
x.reshape(2,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Yeni Boyut Eklemek

In [68]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a.shape

(10,)

In [66]:
a[np.newaxis, : ]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [70]:
a[np.newaxis, : ].shape

(1, 10)

In [74]:
# column vector
a[ : , np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [75]:
a[ :, np.newaxis].shape

(10, 1)

In [76]:
# veya NONE yazarak yapabilirz

In [77]:
a[None, : ]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [78]:
a[ :, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])